add_newline = true
# A minimal left prompt
format = """$python$directory$character"""
# move the rest of the prompt to the right
right_format = """$status$all"""

[character]
# Using Gruvbox green, yellow, and red
success_symbol = "[❯](#b8bb26)[❯](#fabd2f)[❯](#fb4934)"
error_symbol = "[❯](#fb4934)[❯](#fabd2f)[❯](#b8bb26)"
vicmd_symbol = "[❮](#b8bb26)[❮](#fabd2f)[❮](#fb4934)"

[git_branch]
format = '[$branch]($style) '
style = 'bold #b8bb26'  # Gruvbox green

[python]
format = '\($virtualenv\) '

[git_status]
format = '$all_status$ahead_behind '
ahead = '[⬆ ](#d3869b) '      # Gruvbox purple
behind = '[⬇ ](#d3869b) '     # Gruvbox purple
staged = '[✚ ](#b8bb26) '      # Gruvbox green
deleted = '[✖ ](#fb4934) '     # Gruvbox red
renamed = '[➜ ](#d3869b) '     # Gruvbox purple
stashed = '[✭ ](#83a598) '     # Gruvbox blue
untracked = '[◼ ](#ebdbb2) '   # Gruvbox light
modified = '[✱ ](#83a598) '    # Gruvbox blue
conflicted = '[═ ](#fabd2f) '  # Gruvbox yellow
diverged = '⇕ '
up_to_date = ''

[directory]
style = "#83a598"  # Gruvbox blue
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
symbol = '✘ '
